/** Provider-owned external turns: the Agent owns visible settlement and the provider owns private execution. */
import type { Scoped } from '@deepseek-ai/dsh-scope'
import type { Session, SessionId, UserMessage } from '@deepseek-ai/dsh-session'
import type { ReasoningEffortId, TokenUsage } from '@deepseek-ai/dsh-llm'
import type { Agent } from './runtime-types.ts'

/** Frozen route captured when an External Turn is admitted. */
export interface ExternalTurnSelection {
  readonly provider: string
  readonly model: string
  readonly reasoningEffort?: ReasoningEffortId
}

/** Stable public identity attached to an External Turn activity update. */
export interface ExternalTurnActivityIdentity {
  /** Stable operation identity across lifecycle updates for the same item. */
  readonly activityId: string
  /** Stable identity for this specific runtime event. */
  readonly eventId: string
  /** DSH Session and turn which own the external action. */
  readonly sessionId: SessionId
  readonly dshTurn: number
  readonly dshStep: number
  readonly provider: string
  readonly runtimeSource: string
  readonly runtimeVersion: string
  readonly threadId: string
  readonly turnId: string
  readonly itemId: string
  readonly requestId?: string | undefined
  readonly eventKind: string
  readonly terminalState: string
}

/** Public, non-secret activity emitted by an external runtime during a turn. */
export type ExternalTurnEvent =
  | {
    readonly kind: 'command'
    readonly id: string
    readonly command: string
    readonly status: 'started' | 'completed' | 'failed' | 'interrupted'
    readonly identity: ExternalTurnActivityIdentity
  }
  | {
    readonly kind: 'file-change'
    readonly id: string
    readonly path: string
    readonly status: 'created' | 'modified' | 'deleted'
    readonly identity: ExternalTurnActivityIdentity
  }
  | {
    readonly kind: 'approval'
    readonly id: string
    readonly title: string
    readonly status: 'requested' | 'allowed' | 'rejected'
    readonly identity: ExternalTurnActivityIdentity
  }
  | {
    readonly kind: 'turn'
    readonly id: string
    readonly status: 'completed' | 'interrupted' | 'failed'
    readonly identity: ExternalTurnActivityIdentity
  }

/** Safe public text generated by the external turn runtime. */
export interface ExternalTurnPublisher {
  /** @param text - public assistant text from the external runtime, not a tool result. */
  textDelta(text: string): void
  /** @param event - public activity; it is not dispatched through a DSH tool executor. */
  event(event: ExternalTurnEvent): void
}

/** DSH-owned workspace identity verified before an external turn is dispatched. */
export interface ExternalTurnWorkspace {
  readonly identity: string
  readonly cwd: string
}

/** Immutable request passed to a provider-owned external turn executor. */
export interface ExternalTurnRequest {
  readonly agent: Agent
  readonly session: Session
  readonly turn: number
  readonly step: number
  readonly selection: ExternalTurnSelection
  readonly messages: readonly UserMessage[]
  readonly workspaceIdentity: string
  readonly cwd: string
  readonly signal: AbortSignal
  readonly publish: ExternalTurnPublisher
}

/** Truthful result of one completed external runtime turn. */
export interface ExternalTurnResult {
  readonly text: string
  readonly usage?: TokenUsage
  readonly reason?: 'completed' | 'max-tokens'
}

/** Runtime-specific turn owner selected before local prompt/tool assembly. */
export interface ExternalTurnExecutor {
  readonly providerId: string
  resolveWorkspace(session: Session, cwd: string, signal: AbortSignal): Promise<ExternalTurnWorkspace>
  executeTurn(request: ExternalTurnRequest): Promise<ExternalTurnResult>
}

/** Browser-safe metadata returned by a non-LLM external turn provider. */
export interface ExternalModelCatalogEntry {
  readonly id: string
  readonly name: string
  readonly description?: string
  readonly reasoning?: {
    readonly efforts: readonly { readonly id: string; readonly name: string; readonly description?: string }[]
    readonly defaultEffort?: string
  }
}

/** One provider-specific model directory that resolves routes dynamically. */
export interface ExternalModelProvider {
  readonly id: string
  readonly name: string
  listModels(signal?: AbortSignal): Promise<readonly ExternalModelCatalogEntry[]>
  resolveSelection(selection: ExternalTurnSelection, signal?: AbortSignal): Promise<ExternalTurnSelection>
}

/** Deployment registry for runtimes which are not ordinary LLM adapters. */
export interface ExternalModelProviderDirectory {
  listProviders(): readonly ExternalModelProvider[]
}

declare module '@deepseek-ai/cordis' {
  interface Context {
    /** Optional external execution directory; absence preserves ordinary LLM routing. */
    externalModelProviders?: ExternalModelProviderDirectory
  }
  interface Events {
    /**
    * Resolve an optional provider-owned turn executor before local prompt or
    * tool assembly. The default is the existing local AgentLoop path.
    * @param payload.selection - frozen Session route for this turn.
    * @param payload.signal - cancellation signal for the admitted turn.
    * Scope-filtered dispatch (`@deepseek-ai/dsh-scope`): agent-scoped listeners receive only that agent.
    * @mode waterfall
     */
    'agent/resolve-external-turn'(this: Scoped<Agent>, payload: {
      agent: Agent
      selection: ExternalTurnSelection
      signal: AbortSignal
    }, next: () => Promise<ExternalTurnExecutor | undefined>): Promise<ExternalTurnExecutor | undefined>
    /**
     * Public external-runtime activity. This is not a local tool/call event.
    * @param payload.turn - DSH turn that owns the activity.
    * @param payload.step - DSH external step that owns the activity.
    * @param payload.event - sanitized public activity.
    * Scope-filtered dispatch (`@deepseek-ai/dsh-scope`): agent-scoped listeners receive only that agent.
    * @mode emit
     */
    'agent/external-turn-event'(this: Scoped<Agent>, payload: {
      agent: Agent
      turn: number
      step: number
      event: ExternalTurnEvent
    }): void
  }
}
